import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Panini Template</title>
        <meta name="description" content="Generated by Asante" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <header>
          <div className={styles.headerContainer}>
              <button class={styles.headerButton}><Link href="/login-signup">Login</Link></button>
              <button class={styles.headerButton}><Link href="/login-signup">Sign Up</Link></button>
              <button class={styles.headerButton}><Link href="/contact">Contact</Link></button>
              <button class={styles.headerButton}><Link href="/free-content">Free Content</Link></button>
              <button class={styles.headerButton}><Link href="/about">About</Link></button>
              <Link href="/"><img id='imgStyle' alt='Logo Block' src='thumbnail-Educate-Offsite-Logo-sm.png'></img></Link>
          </div>
      </header> */}
      <main className={styles.main}>
        <section id={styles.homeSection} class='test class'>
        <h1 className={styles.title}>
          Welcome to the <a href="">Panini Template!</a>
        </h1>
        </section>
        <section id={styles.about} class={styles.fpDouble}>
          <div class={styles.fpDoubleA}>
            <div className={styles.columnImage}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={200} height={125} />
              <p>Image of a flowchart</p>
              </div>
          </div>
          <div class={styles.fpDoubleB}>
            <h1>A Section <a href="">About Us</a></h1>
            <p>Extra info that's going to explain the IP Licenses obtained and their utilization</p>
            <ol>
              <li>Panini Uno</li>
              <li>Panini Quattro</li>
              <li>Panini Techno</li>
            </ol>
            <button class={styles.buttonSpec}>Yellow Paper</button>
          </div>
        </section>
        <section id={styles.LIPs} class={styles.fpDouble}>
          <div class={styles.fpDoubleA}>
            <h1>Licenses of <a href="">Intellectual Property</a></h1>
            <p>Extra info that's going to explain the IP Licenses obtained and their utilization</p>
            <ol>
              <li>Panini Uno</li>
              <li>Panini Quattro</li>
              <li>Panini Techno</li>
            </ol>
            <button class={styles.buttonSpec}>Contact</button>
          </div>
          <div class={styles.fpDoubleB}>
            <div className={styles.columnImage}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={200} height={125} />
              <p>Image of a flowchart</p>
              </div>
          </div>
        </section>
        <section id={styles.token} class={styles.fpDouble}>
          <div class={styles.fpDoubleA}>
            <h1>Section for <a href="">Paninis (Tokens)</a></h1>
            <p>Extra info that's going to explain the IP Licenses obtained and their utilization</p>
            <ol>
              <li>Panini Uno</li>
              <li>Panini Quattro</li>
              <li>Panini Techno</li>
            </ol>
          </div>
          <div class={styles.fpDoubleB}>
            <div className={styles.columnImage}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={200} height={125} />
              <p>Image of a flowchart</p>
              </div>
          </div>
        </section>
        <section id={styles.roadmap} class={styles.fpSingle}>
            <div class={styles.textAlign}>
              <p>Roadmap</p>
            </div>
            <div class={styles.itemAlign}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={250} height={125} />
            </div>
        </section>
        <section id={styles.team} class={styles.fpSingle}>
        <h1 className={styles.title}>
            Official <a href="">Team</a>
          </h1>
          <div className={styles.grid}>
            <a href="" className={styles.card}>
            <Image src="/profile-pic-02.jpg" alt="Vercel Logo" width={200} height={150} />
              <h2>Macho Macho Man</h2>
              <p>Software Engineer first, CEO second</p>
            </a>
            <a href="" className={styles.card}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={200} height={125} />
              <h2>Macho Man</h2>
              <p>VP first, Software Engineer second</p>
            </a>
            <a href="" className={styles.card}>
            <Image src="/profile-pic-02.jpg" alt="Vercel Logo" width={200} height={125} />
              <h2>Macho Man</h2>
              <p>VP first, Software Engineer second</p>
            </a>
            <a href="" className={styles.card}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={200} height={125} />
              <h2>Macho Man</h2>
              <p>VP first, Software Engineer second</p>
            </a>
            <a href="" className={styles.card}>
            <Image src="/profile-pic-02.jpg" alt="Vercel Logo" width={200} height={125} />
              <h2>Macho Man</h2>
              <p>VP first, Software Engineer second</p>
            </a>
            <a href="" className={styles.card}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={200} height={125} />
              <h2>Macho Man</h2>
              <p>VP first, Software Engineer second</p>
            </a>
          </div>
        </section>
        <section id={styles.tech} class={styles.fpDouble}>
          <div class={styles.fpDoubleA}>
              <h1>A Section for the <a href="">Technology</a> involved</h1>
              <p>Extra info that's going to explain the tech being built and/or going to be built</p>
              <ol>
                <li>Panini Uno</li>
                <li>Panini Quattro</li>
                <li>Panini Techno</li>
              </ol>
              <button class={styles.buttonSpec}>Documentation</button>
            </div>
            <div class={styles.fpDoubleB}>
              <div className={styles.columnImage}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={200} height={125} />
                <p>Image of a flowchart</p>
                </div>
            </div>
        </section>
        <section id={styles.faq} class={styles.fpSingle}>
          <h1 className={styles.title}>
            Section for <a href="">FAQ</a>
          </h1>
          <div class={styles.textAlign}>
            <p>If you don't find the answers to your questions here, email us at <a href="">paninis@paniniclub.io</a></p>
          </div>
        </section>
        <section id={styles.ecosystem} class={styles.fpSingle}>
          <h1 className={styles.title}>
            Ecosystems & <a href="">Partners</a>
          </h1>
          <div className={styles.grid}>
            <a href="" className={styles.card}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={200} height={125} />
              <h2>Macho Macho Man</h2>
              <p>Software Engineer first, CEO second</p>
            </a>
            <a href="" className={styles.card}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={200} height={125} />
              <h2>Macho Man</h2>
              <p>VP first, Software Engineer second</p>
            </a>
            <a href="" className={styles.card}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={200} height={125} />
              <h2>Macho Man</h2>
              <p>VP first, Software Engineer second</p>
            </a>
            <a href="" className={styles.card}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={200} height={125} />
              <h2>Macho Man</h2>
              <p>VP first, Software Engineer second</p>
            </a>
            <a href="" className={styles.card}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={200} height={125} />
              <h2>Macho Man</h2>
              <p>VP first, Software Engineer second</p>
            </a>
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Asante
        </a>
      </footer>
    </div>
  )
}
